name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip-ci')
    runs-on: ubuntu-latest
    name: Run Pre-Commit
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.0
  test:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11'
      - name: Update tools
        run: python -m pip install --upgrade pip setuptools wheel poetry
      - name: Install Project
        run: |
          make install
      - name: Run CI Tests
        run: |
          make ci
  publish:
    needs: [lint,test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.6
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v7.34.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
